service: sample-app
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: src/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
  log-cron:
    handler: src/scheduler.handler
    events:
      - schedule:
          rate: cron(0 3-13 ? * MON-FRI *)
          enabled: false
